### PR TITLE
Add `vtype` for RR/OR

### PR DESCRIPTION
**Pull request by bwiernik**
I also documented the `vtype` options for RD, which were available but undocumented.

Changes:

1. Add `vtype = "AV"` for RR and OR measures following the existing structure for RD. The `vtype = "AV"` options will have very similar properties to the sample-size weighted estimator described by Bakbergenuly et al. (2019) and is much easier to implement in the existing code structure.

2. Add `vtype = "UB"` for RR and OR measures following the existing structure for RD by subtracting 1 from the total group sample sizes.

3. Document the `vtype` options for RR, OR, and RD. RD options were previously available, but undocumented.

Ref:
Bakbergenuly, I., Hoaglin, D. C., & Kulinskaya, E. (2019). Simulation study of estimating between-study variance and overall effect in meta-analysis of odds-ratios. arXiv. http://arxiv.org/abs/1902.07154

### CODE REVIEW

**Comment by bwiernik** [comment]
@wviechtb The failing checks don't seem to be related to these changes?

**Comment by wviechtb** [comment]
Yeah, `Rcgmin` and `Rvmmin` are archived, which is the problem. I currently have a large pending update of metafor sitting in my local repo that I need to finish up (which also touches `escalc()`), so to avoid any hassles with merging, I cannot pull this in right now. Will try to do so after the update. Not sure if you would have to fetch any updates coming from my side in the meantime. We will get this sorted out.

**Comment by wviechtb** [comment]
Okay, now had a chance to look at this. It's nice to add this, but `UB` for the log risk and odds ratio isn't quite right. For a single binomial proportion, one can easily derive the expected value of $\frac{p(1-p)}{n}$ which is $\left(\frac{n-1}{n}\right)\frac{\pi(1-\pi)}{n}$, which shows that $\frac{p(1-p)}{n-1}$ is unbiased (so for RD, we just do this for the first and second proportion). But this doesn't transfer to $\ln(p)$ or $\ln(p/(1-p))$. So I would suggest to remove `UB` for those measures.

**Comment by wviechtb** [comment]
After a long time, I've now implemented `type="AV"` for measures `"RR"` and `"OR"`, but this is not currently documented, as I would like to run some simulations first to see how this actually affects things. In fact, the same applies to measure `"RD"`. Of course using `type="AV"` makes perfect sense when the true proportions within groups are actually homogeneous, but this is a rather restrictive assumption since this goes beyond assuming homogeneity of the RD/RR/OR values (which does not imply/require homogeneity of the proportions within groups). So using `type="AV"` is a rather restrictive assumption and how this performs (when this assumption is violated) requires running some simulation studies. For reasons explained earlier, `vtype="UB"` does not carry over to measures `"RR"` and `"OR"` so this was left out. I am closing this pull request now to clear the queue.

**Pull request closed without merging**
